In [1]:
import numpy
import torch

In [2]:
#创建标准正态分布矩阵，维度可变
a = torch.randn(2, 3, 3, 1)
a

tensor([[[[-0.7150],
          [-0.2528],
          [-0.9498]],

         [[ 1.9665],
          [ 1.3879],
          [-1.3074]],

         [[ 0.4186],
          [ 0.9843],
          [ 0.4373]]],


        [[[ 0.4156],
          [ 0.2733],
          [-0.8496]],

         [[-0.1488],
          [ 0.2617],
          [ 0.2777]],

         [[ 0.2505],
          [ 0.3674],
          [-0.8372]]]])

In [3]:
#创建常数tensor
torch.tensor(1.)

tensor(1.)

In [4]:
#输出a的维度
a.shape

torch.Size([2, 3, 3, 1])

In [5]:
#输出a在矩阵形式下和常量形式下的形状
a = torch.randn(2, 3, 3, 1)
print(a.size())
print(a.shape)
a = torch.tensor(3.9)
print(a.size())
print(a.shape)

torch.Size([2, 3, 3, 1])
torch.Size([2, 3, 3, 1])
torch.Size([])
torch.Size([])


In [6]:
#torch也可以指定其中的数据类型,torch.Tensor默认为float64
print(torch.tensor(3.9, dtype=torch.float32))
print(torch.FloatTensor([3.9]))

tensor(3.9000)
tensor([3.9000])


In [7]:
import numpy as np

#通过numpy创建全1矩阵
print(np.ones([2, 3]))

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#通过numpy数组转换为tensor
a = torch.from_numpy(np.ones([2, 3]))
print(list(a.shape))
#返回tensor的维度数量
print(a.dim())
#输出tensor的元素数量
print(a.numel())

[2, 3]
2
6


In [9]:
#创建全0矩阵
a = torch.zeros([2, 3])
print(a)
#输出a某个维度下的通道数量
print(a.size(0))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
2


In [10]:
#创建数组列表
np.array([2, 3.3])

array([2. , 3.3])

In [11]:
#创建未初始化的tensor
torch.empty(2, 3)

tensor([[2.6405e-06, 1.0368e-11, 1.6614e-07],
        [8.5410e+20, 2.1744e+23, 2.5812e-06]])

In [12]:
#设置默认类型
torch.set_default_tensor_type(torch.DoubleTensor)
torch.empty(2, 3).type()

'torch.DoubleTensor'

In [13]:
#创建均匀分布的tensor，范围为[0,1)
a = torch.rand(2, 3)
print(a)
#randn_like(a)创建与a形状相同的tensor
a = torch.randn_like(a)
print(a)

tensor([[0.6143, 0.8127, 0.2493],
        [0.4560, 0.2913, 0.9702]])
tensor([[ 1.2416,  0.0534,  0.9366],
        [ 0.5682,  1.0035, -1.9146]])


In [14]:
#创建自定义的正态分布
a = torch.normal(mean=torch.full([10], 1.0), std=torch.arange(1, 0, -0.1))
print(a)
#创建自定义常数填充的tensor
a = torch.full([2, 3], 9.0)
print(a)

tensor([2.2642, 1.5173, 1.4778, 1.2465, 1.5079, 1.4614, 0.5066, 0.6595, 0.8414,
        0.9782])
tensor([[9., 9., 9.],
        [9., 9., 9.]])


In [15]:
#创建等差数列
print(torch.linspace(0, 10, steps=5))
#创建等比数列,默认底数为10
print(torch.logspace(0, -1, steps=5))

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([1.0000, 0.5623, 0.3162, 0.1778, 0.1000])


In [16]:
#创建单位矩阵
torch.eye(3,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [17]:
#创建0到n随机打乱的数列，用于shuffle
idx=torch.randperm(2)
print(idx)
a=torch.rand(3,4)
print(a)
#按照idx中的顺序输出batchsize中的几个
print(a[idx])

tensor([0, 1])
tensor([[0.5840, 0.4875, 0.2912, 0.6534],
        [0.0105, 0.1423, 0.0882, 0.9521],
        [0.2439, 0.5700, 0.8023, 0.7986]])
tensor([[0.5840, 0.4875, 0.2912, 0.6534],
        [0.0105, 0.1423, 0.0882, 0.9521]])


In [18]:
#索引与切片
a=torch.randn(2,3,28,28)
print(a[0].shape)
print(a[:2].shape)
print(a[:2,1:,:,:].shape)
print(a[:2,-1,:,:].shape)
print(a.index_select(3,torch.tensor([0,1,2])).shape)
x=torch.randn(3,4)
mask=x.ge(0.5)
#take选择tensor展平后的序数
print(torch.take(x,torch.tensor([0,3,5])))
#masked_select根据掩码矩阵进行选择
torch.masked_select(x,mask)

torch.Size([3, 28, 28])
torch.Size([2, 3, 28, 28])
torch.Size([2, 2, 28, 28])
torch.Size([2, 28, 28])
torch.Size([2, 3, 28, 3])
tensor([ 1.9714,  0.7016, -0.1678])


tensor([1.9714, 0.7016, 1.8111, 0.9175])

In [19]:
a=torch.rand(4,1,28,28)
#view可以将矩阵变形
print(a.view(4,28*28))
#unsqueeze可以在指定位置增加维度
print(a.unsqueeze(0).shape)
#squeeze可以去除指定位置的维度,但是该维度必须为1
print(a.squeeze(1).shape)
#expend可以将维度为1的进行扩展，方法为复制
print(a.expand(4,3,28,28).shape)
#repeat可以将指定维度进行重复
print(a.repeat(4,3,1,1).shape)
#t()可以将矩阵转置
print(a[0,0,:,:].t().shape)

tensor([[0.3998, 0.6095, 0.6115,  ..., 0.2285, 0.2856, 0.9434],
        [0.8531, 0.5300, 0.9844,  ..., 0.3234, 0.7378, 0.2208],
        [0.4422, 0.9050, 0.4034,  ..., 0.4003, 0.8965, 0.5094],
        [0.4891, 0.7168, 0.4915,  ..., 0.8313, 0.2751, 0.1454]])
torch.Size([1, 4, 1, 28, 28])
torch.Size([4, 28, 28])
torch.Size([4, 3, 28, 28])
torch.Size([16, 3, 28, 28])
torch.Size([28, 28])


In [20]:
#permute可以将维度按照指定顺序排列，transpose可以交换指定维度，使用后尽量加contiguous
a=torch.rand(4,3,28,28)
print(a.transpose(1,3).contiguous().shape)
print(a.permute(1,2,3,0).contiguous().shape)
#将tensor转为numpy数组
a=a.numpy()
#numpy的transpose可以将维度按照某个顺序重新排列
print(a.transpose(0,3,2,1).shape)

torch.Size([4, 28, 28, 3])
torch.Size([3, 28, 28, 4])
(4, 28, 28, 3)


In [21]:
#eq可以进行元素级别的比较，返回一个bool类型的tensor,all可以判断所有元素是否为True,any可以判断是否有一个元素为True
a=torch.rand(4,3,28,28)
print(torch.all(torch.tensor([True,False,True])))
a2=torch.rand_like(a)
print(torch.all(torch.eq(a,a2)))
print(torch.any(torch.tensor([True,False,True])))
print(torch.any(torch.eq(a,a2)))

tensor(False)
tensor(False)
tensor(True)
tensor(False)


In [39]:
#tensor具有广播机制，可以将维度不同的tensor进行运算，但是维度必须为1或者缺失，我的评价是尽量别用混淆视听
#torch.cat可以将tensor按照指定维度进行拼接
a=torch.rand(4,32,8)
b=torch.rand(5,32,8)
print(torch.cat([a,b],dim=0).shape)
#stack可以将tensor按照指定维度进行堆叠
a=torch.rand(4,3,16,32)
b=torch.rand(4,3,16,32)
print(torch.stack([a,b],dim=2).shape)
#split可以将tensor按照指定维度进行切分
c=torch.stack([a,b],dim=0)
#[]指定每个块的维度或者输入数字指定块大小
aa,bb=c.split([1,1],dim=0)
d=c.split(1,dim=0)
print(c.shape)
print(d.shape)
print(aa.shape)

torch.Size([9, 32, 8])
torch.Size([4, 3, 2, 16, 32])
torch.Size([2, 4, 3, 16, 32])
torch.Size([1, 4, 3, 16, 32])


In [64]:
#使用add相加
a=torch.rand(3,4)
b=torch.rand(4)
print(a+b)
print(torch.add(a,b))
#使用matmul进行矩阵相乘
print(a@b)

print(torch.matmul(a,b))
#mm函数只对2d生效
b=torch.rand(4,3)
print(torch.mm(a,b))
#pow可以对tensor进行幂运算
print(a.pow(2))
#exp可以对tensor进行指数运算
print(a.exp())
#log可以对tensor进行对数运算
print(a.log())
#max可以对tensor进行最大值运算
print(a.max())
#median可以对tensor进行中位数运算
print(a.median())
#clamp可以对tensor进行截断运算
print(a.clamp(0.2,0.8))
#norm可以对tensor进行范数运算
print(a.norm(2,dim=0))
#sum可以对tensor进行求和运算
print(a.sum(dim=0))
#mean可以对tensor进行求均值运算
print(a.mean(dim=0))
#prod可以对tensor进行求积运算
print(a.prod(dim=0))
#argmin可以对tensor进行求最小值索引运算
print(a.argmin(dim=0))
#argmax可以对tensor进行求最大值索引运算,keepdim可以保持维度
print(a.argmax(dim=0))
print(a.argmax(dim=0,keepdim=True))
#kthvalue可以对tensor进行求第k小值运算
print(a.kthvalue(2,dim=0))
#topk可以对tensor进行求前k大值运算
print(a.topk(2,dim=0))
#where 可以对tensor进行条件选择运算
print(torch.where(a>0.5,a,torch.ones_like(a)))
#gather可以对tensor进行索引运算,第一个参数为索引矩阵，第二个参数为索引维度
print(a)
print(torch.gather(a,1,torch.tensor([[0,1],[2,0],[3,1]])))

tensor([[0.5383, 1.1240, 1.0319, 1.5863],
        [1.0658, 1.5687, 1.2679, 1.8527],
        [1.2618, 1.6943, 1.0569, 1.6539]])
tensor([[0.5383, 1.1240, 1.0319, 1.5863],
        [1.0658, 1.5687, 1.2679, 1.8527],
        [1.2618, 1.6943, 1.0569, 1.6539]])
tensor([1.1567, 2.1297, 1.9570])
tensor([1.1567, 2.1297, 1.9570])
tensor([[0.9138, 0.8833, 1.0083],
        [1.5576, 1.8807, 2.0061],
        [1.4142, 1.9953, 1.9863]])
tensor([[0.0171, 0.1470, 0.0854, 0.4003],
        [0.4331, 0.6859, 0.2790, 0.8084],
        [0.7295, 0.9096, 0.1007, 0.4904]])
tensor([[1.1395, 1.4673, 1.3394, 1.8826],
        [1.9311, 2.2891, 1.6959, 2.4574],
        [2.3493, 2.5953, 1.3734, 2.0143]])
tensor([[-2.0356, -0.9586, -1.2302, -0.4578],
        [-0.4184, -0.1885, -0.6382, -0.1064],
        [-0.1577, -0.0474, -1.1480, -0.3563]])
tensor(0.9537)
tensor(0.6327)
tensor([[0.2000, 0.3834, 0.2922, 0.6327],
        [0.6581, 0.8000, 0.5282, 0.8000],
        [0.8000, 0.8000, 0.3173, 0.7003]])
tensor([1.0861, 1.3200, 0.6

In [67]:
#linspace可以生成等差数列
a=torch.linspace(-100,100,10)
print(a)
#sigmoid,tanh,relu可以对tensor进行激活运算
print(torch.sigmoid(a))
print(torch.tanh(a))
print(torch.relu(a))

tensor([-100.0000,  -77.7778,  -55.5556,  -33.3333,  -11.1111,   11.1111,
          33.3333,   55.5556,   77.7778,  100.0000])
tensor([3.7201e-44, 1.6655e-34, 7.4564e-25, 3.3382e-15, 1.4945e-05, 9.9999e-01,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00])
tensor([-1.0000, -1.0000, -1.0000, -1.0000, -1.0000,  1.0000,  1.0000,  1.0000,
         1.0000,  1.0000])
tensor([  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,  11.1111,  33.3333,
         55.5556,  77.7778, 100.0000])


In [108]:
import torch.nn.functional as F
x=torch.ones(1)
print(x)
w=torch.full([1],2,dtype=torch.float32)
print(w)
#mse_loss可以计算均方误差,requires_grad_可以使得tensor具有梯度,需要类型是float
w.requires_grad_()
mse=F.mse_loss(torch.ones(1),x*w)
print(mse)
print(torch.autograd.grad(mse,[w]))
#backward可以梯度反向传播,计算图有可能清除内存无法第二次梯度传播
w=torch.full([1],2,dtype=torch.float32,requires_grad=True)
mse=F.mse_loss(torch.ones(1),x*w)
mse.backward()
print(w.grad)
a=torch.rand(3)
#requires_grad_可以使得tensor具有梯度,需要类型是float
a.requires_grad_()
print(a.requires_grad)
#softmax可以对tensor进行归一化运算
a=torch.rand(3,requires_grad=True)
p=F.softmax(a,dim=0)
print(p)
# 对矩阵使用需要backward的过程是对各个元素进行求导，然后点成梯度权重张量,retrian_graph=True可以保留计算图,但会占用内存
p.backward(torch.tensor([1.0,0.0,0.0]),retain_graph=True)
# autograd.grad可以对tensor进行求导运算
print(torch.autograd.grad(p[1],[a],retain_graph=True))

tensor([1.])
tensor([2.], dtype=torch.float32)
tensor(1., grad_fn=<MseLossBackward0>)
(tensor([2.], dtype=torch.float32),)
tensor([2.], dtype=torch.float32)
True
tensor([0.3363, 0.3773, 0.2865], grad_fn=<SoftmaxBackward0>)
(tensor([-0.1269,  0.2349, -0.1081]),)


In [109]:
#cross_entropy可以对tensor进行交叉熵运算,比起null_loss,他先进行了softmax运算，再取log
x=torch.randn(1,784)
w=torch.randn(10,784)
logits=x@w.t()
pred=F.softmax(logits,dim=1)
pred_log=torch.log(pred)
#交叉熵需要指定多少个标签有效
print(F.cross_entropy(logits,torch.tensor([3])))
print(F.nll_loss(pred_log,torch.tensor([3])))


tensor(6.7605)
tensor(6.7605)


In [6]:
#nn.Module可以将网络模型封装成一个类,Linear可以实现全连接层,(in,out)
import torch.nn.functional as F
layer1=torch.nn.Linear(784,200)
print(layer1.weight.shape)
x=torch.randn(2,784)
x=layer1(x)
#inplace=True可以使得原tensor改变
x=F.relu(x,inplace=True)
print(x)

torch.Size([200, 784])
tensor([[0.0000e+00, 8.0869e-02, 1.5389e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         3.1340e-01, 0.0000e+00, 8.1614e-01, 0.0000e+00, 0.0000e+00, 6.0517e-01,
         0.0000e+00, 3.1546e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 4.9117e-02,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.5137e+00,
         0.0000e+00, 4.0553e-01, 1.2205e+00, 6.5303e-01, 3.7307e-01, 0.0000e+00,
         7.8382e-01, 3.6775e-01, 0.0000e+00, 3.4816e-01, 7.6712e-01, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 1.0078e+00, 2.8184e-01, 3.1037e-01, 0.0000e+00,
         0.0000e+00, 6.4972e-01, 7.9018e-01, 5.1738e-02, 4.9232e-01, 4.4398e-01,
         0.0000e+00, 0.0000e+00, 1.1294e-01, 3.2224e-01, 0.0000e+00, 3.0268e-01,
         0.0000e+00, 4.3261e-01, 0.0000e+00, 2.6344e-01, 1.4409e-01, 0.0000e+00,
         0.0000e+00, 3.4651e-02, 0.0000e+00, 4.1353e-03, 1.9618e-01, 2.1611e-01,
         0.0000e+00, 0.0000e+00, 7.9720e-01, 0.0000e+00, 0.0000e+00, 8.9673e-01,
     

In [10]:
#device可以指定运算设备
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
#torch.utils.data.random_split可以将数据集切分成训练集和测试集
train_db=torch.randn(60000,28*28)
train_db,val_db,test_db=torch.utils.data.random_split(train_db,[50000,5000,5000])
print(len(train_db),len(val_db),len(test_db))


50000 5000 5000
